### ISSUE TITLE
error running new version of import_realtime_ops.py

### ISSUE THREAD

**Issue by oxarbitrage** [oxarbitrage/bitshares-python-api-backend#15]
```
Traceback (most recent call last):
  File "import_realtime_ops.py", line 8, in <module>
    import api
ImportError: No module named api
```

seems that needs an `__init__.py` or something in the postgres directory to make it work. @knaperek ?

**Comment by knaperek** [comment]
As I mentioned earlier (in [PR#8](https://github.com/oxarbitrage/bitshares-python-api-backend/pull/8)) you need to add the absolute path to the source code into `PYTHONPATH` environment variable.

**Comment by oxarbitrage** [comment]
thank you, i missed that. still, seems to don't work exactly as that:

```
root@alfredo:~/bitshares-munich/explorer/repo/lastv/bitshares-python-api-backend/postgres# PYTHONPATH=/root/bitshares-munich/explorer/repo/lastv/bitshares-python
-api-backend
root@alfredo:~/bitshares-munich/explorer/repo/lastv/bitshares-python-api-backend/postgres# echo $PYTHONPATH
/root/bitshares-munich/explorer/repo/lastv/bitshares-python-api-backend
root@alfredo:~/bitshares-munich/explorer/repo/lastv/bitshares-python-api-backend/postgres# python import_realtime_ops.py 
Traceback (most recent call last):
  File "import_realtime_ops.py", line 8, in <module>
    import api
ImportError: No module named api
root@alfredo:~/bitshares-munich/explorer/repo/lastv/bitshares-python-api-backend/postgres# 
```

need to add this to the main README as i tried the docker but i had a hard time with it probably caused by my server configuration so i had to run it in the traditional way :)

thanks again.

**Comment by knaperek** [comment]
What's in your $PYTHONPATH? The `api.py` module is obviously there (check the source tree), so it should not crash when importing it (as long is your PYTHONPATH is set correctly).

**Comment by oxarbitrage** [comment]
i have the root of the porject in $PYTHONPATH:

```
root@alfredo:~# cd $PYTHONPATH 
root@alfredo:~/bitshares-munich/explorer/repo/lastv/bitshares-python-api-backend# ls
Dockerfile  README.md  api.py   config.py   docker-compose.override.yml  explorer_config.env  requirements  wsgi.py
LICENSE     api.ini    api.pyc  config.pyc  docker-compose.yml           postgres             uwsgi.ini     wsgi.pyc
root@alfredo:~/bitshares-munich/explorer/repo/lastv/bitshares-python-api-backend# 
```

**Comment by knaperek** [comment]
Try adding `__init__.py` into the root folder.

**Comment by Zapata** [comment]
I think this could be closed as there is no more  import_realtime_ops.py as they are taken directly from Elastic Search.
