### ISSUE TITLE
refactor get_objects to use ES when object is op

### ISSUE THREAD

**Issue by oxarbitrage** [oxarbitrage/bitshares-python-api-backend#19]
current implementation of `lastnetworkops` will call `_get_object` : https://github.com/oxarbitrage/bitshares-python-api-backend/blob/master/api.py#L522 with `operation_id`

this situation makes non possible to run all the explorer backend with 1 node as we need plugin `elasticsearch` and `account_history` activate at the same time. this is not possible in 1 node.

need to change `_get_object` to get data from ES when object type is operation or make new call for this purpose.

**Comment by Zapata** [comment]
I think this is fixed and can be closed.

**Comment by oxarbitrage** [comment]
yea, thanks.
