### ISSUE TITLE
Proposal for API V2.

### ISSUE THREAD

**Issue by Zapata** [oxarbitrage/bitshares-python-api-backend#33]
Currently there are many possible improvements to the API.

Here is a placeholder to regroup all those changes, to propose a new `/v2/` base path.

- `/operation*` return a list, it should not, just the operation
- `/account`, `/full_account` returns a list, it should not, just the account
- `/get_assets`, `/get_asset_and_volume` returns a list, it should not, just return the asset
- `/get_object` returns a list, it should not, just the object
- `/get_settle_orders` is wierd, parameters do not match core doc
- /getlastblocknumb**h**er typo, to be coherent is should be `/get_last_block_number`
- `/top_*:` should returns objects with named fields instead of array of array (see also https://github.com/oxarbitrage/bitshares-explorer-api/issues/5)
- `/*_votes`: should return objects with named fields instead of array of array 
- `/get_witnesses`: actually return an array of array of one object, should just be array of object
- `get_most_active_markets`: should return objects with named fields instead of array of array  (see also https://github.com/oxarbitrage/bitshares-explorer-api/issues/5)
- (es_wrapper) `/get_account_history`: operation_type should be an int10
- (es_wrapper) `/get_single_operation`: should return object instead of array
- `/get_account_history_pager_elastic` is incoherent with `/get_operation_full_elastic` (following https://github.com/oxarbitrage/bitshares-explorer-api/pull/28)
- (es_wrapper) do json.load on `op` and `result` fields
- put all udf calls under `/udf`

In order to avoid breaking current api the proposal is to make a new /v2 endpoint. If clients could be updated we can stay on the current endpoint.

**Comment by Zapata** [comment]
- Rename `/operation_full_elastic` in `/operation`
- Rename `/account_history_pager_elastic` in  `/account_history`

**Comment by Zapata** [comment]
Remove `get_` prefix from all paths for consistency.

**Comment by Zapata** [comment]
Put all es wrapper calls under `/es/` path.

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-explorer-api/pull/45
