### ISSUE TITLE
deep search failing

### ISSUE THREAD

**Issue by oxarbitrage** [oxarbitrage/bitshares-python-api-backend#39]
`get_account_history_pager_elastic` seems to be failing in current ES versions for accounts with a good number of operations: http://185.208.208.184:5000/account_history_pager_elastic?account_id=1.2.1144936&page=24676

Some different approach as https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html should be done.

**Comment by oxarbitrage** [comment]
After the last refactor the link is a bit different but bug still present:

```
oxarbitrage@oxarbitrage-Lenovo-ideapad-320S-14IKB:~/CLionProjects/private_testnet_htlc/bitshares-core$ curl "https://explorer.bitshares-kibana.info/es/account_history?account_id=1.2.450921&from_=9900&size=150&sort_by=block_data.block_time&type=data&agg_field=operation_type"
{
  "detail": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
  "status": 500,
  "title": "Internal Server Error",
  "type": "about:blank"
}
oxarbitrage@oxarbitrage-Lenovo-ideapad-320S-14IKB:~/CLionProjects/private_testnet_htlc/bitshares-core$ 
```

**Comment by Zapata** [comment]
For the reference here is the error:

` ` ` 
TransportError: TransportError(500, u'search_phase_execution_exception', u'Result window is too large, from + size must be less than or equal to: [10000] but was [10050]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.')
` ` ` 

In order to solve that we can use `search_after`, however this will bring a small change in the API. 
Intead of the parameter `from_=<last_operation_count>` we will need to use `search_after=<last_value_of_the_sort_by_field>`.

As an example:

```
curl "http://localhost:5000/es/account_history?account_id=1.2.450921&size=150&sort_by=operation_id_num"
``` 

returns 150 operations with the last one with `"operation_id_num": 106441267`. 
The next call should be:

 ```
curl "http://localhost:5000/es/account_history?account_id=1.2.450921&size=150&sort_by=operation_id_num"&search_after=106441267
```

`sort_by` and `search_after` might use any field from the `bitshares-*` index. However in order to have consistent result when the `search_after` field is used, a field that uniquely sort all the documents should be used. This is not the case of `block_data.block_time` as an account can have multiple operations in the same block. `operation_id_num` or `account_history.operation_id.keyword` are more appropriate (the first one is faster that the later).

**Comment by oxarbitrage** [comment]
Lets change the API. Do the search after with `operation_id_num` as you suggest.

**Comment by oxarbitrage** [comment]
hmm, sorry. Make new call. `deep_account_history`.

**Comment by oxarbitrage** [comment]
We will deprecate it later but keep for a while.

**Comment by Zapata** [comment]
Sorry just seen your comment, I will update the pull request.
I think we can handle both parameters to make it backward compatible.

**Comment by oxarbitrage** [comment]
My apologies, i doubted there but i think that the ES wrapper is even more used than the explorer parts(remember when they were separated) so i suppose it will be better to remain compatible. Let me know what do you think, i am open to just change it, backward compatible will be the best.

**Comment by Zapata** [comment]
Last pull request is backward compatible. 
It's even better than before, should have did that since the beginning.

**Comment by oxarbitrage** [comment]
Merged @Zapata pull request for this. I will leave the issue open until i can install this in a production enviroment.

I think the iteration for a user account haves to be by using the `account_history.sequence` field. This is an incremental only for the account so for example:

```
alfredo@alfredo-System-Product-Name:~/PycharmProjects$ curl "http://localhost:5000/es/account_history?account_id=1.2.450921&search_after=10000&size=1&sort_by=account_history.sequence&type=data&agg_field=operation_type"
[
  {
    "account_history": {
      "account": "1.2.450921",
      "id": "2.9.112822260",
      "next": "2.9.112820853",
      "operation_id": "1.11.111231020",
      "sequence": 10001
    },
...
```

Will get us operation 10001 for the account, and:

```
alfredo@alfredo-System-Product-Name:~/PycharmProjects$ curl "http://localhost:5000/es/account_history?account_id=1.2.450921&search_after=9900&size=150&sort_by=account_history.sequence&type=data&agg_field=operation_type"
[
  {
    "account_history": {
      "account": "1.2.450921",
      "id": "2.9.112792717",
      "next": "2.9.112792516",
      "operation_id": "1.11.111202593",
      "sequence": 9901
    },
...
  {
    "account_history": {
      "account": "1.2.450921",
      "id": "2.9.112801097",
      "next": "2.9.112800843",
      "operation_id": "1.11.111210642",
      "sequence": 9931
    },
...
  {
    "account_history": {
      "account": "1.2.450921",
      "id": "2.9.112848421",
      "next": "2.9.112848204",
      "operation_id": "1.11.111256340",
      "sequence": 10050
    },
...
```

Will get us the operations from 9901 up to 10050.

**Comment by oxarbitrage** [comment]
By using `account_history.sequence` the behaviour will be the same as using `from_`

**Comment by Zapata** [comment]
Nice spot!

Note that `type=data&agg_field=operation_type` are useless in the query. `type=data` is the default, and `agg_field` is only used when `type != 'data'`.

**Comment by oxarbitrage** [comment]
Added the fix to https://explorer.bitshares-kibana.info/apidocs/#!/wrapper/api_es_wrapper_get_account_history

Now we we can do: 

```
curl "https://explorer.bitshares-kibana.info/es/account_history?account_id=1.2.450921&search_after=10000&size=1&sort_by=account_history.sequence"
```

**Comment by startailcoon** [comment]
Thanks!

**Comment by oxarbitrage** [comment]
Added suport in open-explorer, https://github.com/oxarbitrage/open-explorer/commit/5b47e3d80d0572888aa960c60c380df4f6aa846b

Closing here.

**Comment by startailcoon** [comment]
@oxarbitrage I'm having some issues when testing this out, not sure if I'm doing something wrong.

Both these requests return the result from the first TX in the account.

`https://explorer.bitshares-kibana.info/es/account_history?account_id=1.2.1057595&search_after=0&size=2&sort_by=block_data.block_time`

`https://explorer.bitshares-kibana.info/es/account_history?account_id=1.2.1057595&search_after=20000&size=2&sort_by=block_data.block_time`

**Comment by oxarbitrage** [comment]
Need to use `account_history.sequence` as sort by, something like:

https://explorer.bitshares-kibana.info/es/account_history?account_id=1.2.1057595&search_after=0&size=2&sort_by=account_history.sequence

https://open-explorer.io/#/accounts/1.2.1057595 only haves 364 operations so a query with `search_after=20000` will return empty.

Can do:
https://explorer.bitshares-kibana.info/es/account_history?account_id=1.2.1057595&search_after=100&size=2&sort_by=account_history.sequence and should work.
