### ISSUE TITLE
operation_type filter not working properly

### ISSUE THREAD

**Issue by bitphage** [oxarbitrage/bitshares-python-api-backend#47]
Try get 0 operation:

```
curl -X GET --header 'Accept: application/json' 'http://185.208.208.184:5000/es/account_history?account_id=1.2.25010&operation_type=0&size=3&from_date=2015-10-10&to_date=now&sort_by=block_data.block_time&type=data&agg_field=operation_type'
```

Results contains different operation types, not only 0.

**Comment by oxarbitrage** [comment]
Seems to be an issue with the 0(transfer) types as the 0 is used as default. If you change to for example:

`curl -X GET --header 'Accept: application/json' 'http://185.208.208.184:5000/es/account_history?account_id=1.2.25010&operation_type=1&size=3&from_date=2015-10-10&to_date=now&sort_by=block_data.block_time&type=data&agg_field=operation_type'`

It works fine, ill fix it as soon as i can, thanks for the report.

**Comment by oxarbitrage** [comment]
fixed at https://github.com/bitshares/bitshares-explorer-api/commit/bf9b9bfa19b4821b08c176727410393bb5ddd34a

thanks again.
