### ISSUE TITLE
Feature request: get transaction by id

### ISSUE THREAD

**Issue by abitmore** [oxarbitrage/bitshares-python-api-backend#48]
Can we have an API to fetch transaction by txid? Can return block number, sequence in block, raw json of the transaction.

**Comment by oxarbitrage** [comment]
Api already exist: https://explorer.bitshares-kibana.info/es/trx?trx=738be2bd22e2da31d587d281ea7ee9bd02b9dbf0&size=10

For some more info check: https://explorer.bitshares-kibana.info/apidocs/#!/wrapper/api_es_wrapper_get_trx

This api call is in charge of feeding the open-explorer transaction pages such as https://open-explorer.io/#/txs/738be2bd22e2da31d587d281ea7ee9bd02b9dbf0

**Comment by abitmore** [comment]
Oh, it's in the `wrapper` group, I overlooked. Thanks.
