### ISSUE TITLE
Requesting: Verbose keys for 'get_most_active_markets' and 'top_proxies'

### ISSUE THREAD

**Issue by grctest** [oxarbitrage/bitshares-python-api-backend#5]
Hey,

I was looking to integrate both 'get_most_active_markets' and 'top_proxies' into the Bitshares Google Assistant, but the keys for each of the items are simply 0,1,2,3,4 etc, and I don't know what they're representing.

Would we be able to provide informative key strings please? It's OK to not have the key strings for say 'top_uias' because it's just the uia name & the amount traded, but for functions which return many rows it's not immediately clear what they're supposed to represent.

Thanks for all the effort you've put into developing this repo, much appreciated & keep up the great work! 👍

**Comment by Zapata** [comment]
Should be better with #45 .

```
$ curl "http://localhost:5000/most_active_markets" | head
[
  {
    "24h_volume": 185.8243984,
    "base_id": "1.3.4344",
    "latest_price": 275.8602312341685,
    "pair": "ALGO.BCH/ALGO.USDT",
    "quote_id": "1.3.4906"
  },
  {               
```
and

```
$ curl "http://localhost:5000/top_proxies" | head
[
  {
    "bts_weight": 27883931119902,
    "bts_weight_percentage": 13.727518836791205,
    "followers": 3,
    "id": "1.2.1109330",
    "name": "beos"
  },
  {
```

**Comment by oxarbitrage** [comment]
thank you @Zapata , closing this one.
