### ISSUE TITLE
Create api to convert operation_type number to name

### ISSUE THREAD

**Issue by oxarbitrage** [oxarbitrage/bitshares-python-api-backend#50]
It is common when developing an app using this api that you end up with an operation type, this can come from a `get_block` call, from elasticsearch, etc.

A new api call can be created that match id with name, should be something as:

`get operation_type_name(0)` returns: `transfer`
`get operation_type_name(1)` returns: `limit_order_create_operation`
...

Operation names can be obtained from: https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/include/graphene/chain/protocol/operations.hpp#L50-L105 where `transfer_operation` is 0.

If created, will save some time to the application developer avoiding the creation of this map on its own app.

**Comment by Zapata** [comment]
The link does not work , here is the correct one: https://github.com/bitshares/bitshares-core/blob/master/libraries/protocol/include/graphene/protocol/operations.hpp#L50-L105

I suggest that we do:
    - `/operation_type?id=0` returns: `{ "id": 0, "name": "transfer" }`
    - `/operation_type?name=transfer` returns: `{ "id": 0, "name": "transfer" }`
    - `/operation_types` returns `[ { "id": 0, "name": "transfer" }, ... ]`

It seems more flewible to me, as we have both ways, and the caller can easely cache all values if needed.

**Comment by Zapata** [comment]
I can work on this, please assign it to me.

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-explorer-api/pull/61
