### ISSUE TITLE
udf wrapper history failing

### ISSUE THREAD

**Issue by oxarbitrage** [oxarbitrage/bitshares-python-api-backend#55]
There is something wrong with the history call to the udf wrapper:
https://open-explorer.io/#/markets/BTS/CNY
is calling: https://explorer.bitshares-kibana.info/udf/history?symbol=CNY_BTS&resolution=D&from=1532451252&to=1563555312 nut not working.

however when the sample here is tried it seems to work ok: https://explorer.bitshares-kibana.info/apidocs/#!/udf/api_udf_get_history

**Comment by Zapata** [comment]
For the record:

```
$ curl "http://localhost:5000/udf/history?symbol=CNY_BTS&resolution=D&from=1532451252&to=1563555312"
....
File "/home/zapata/Projects/bitshares/bitshares-explorer-api/api/udf.py", line 174, in get_history
    left = datetime.fromtimestamp(int(result['t'][-1]+1)).strftime('%Y-%m-%dT%H:%M:%S')
NameError: global name 'result' is not defined
```

**Comment by Zapata** [comment]
I take the issue, please assign it to me.

**Comment by oxarbitrage** [comment]
fixed by https://github.com/bitshares/bitshares-explorer-api/pull/58
