### ISSUE TITLE
schema.txt is not up to date: column and table missing

### ISSUE THREAD

**Issue by shesio** [oxarbitrage/bitshares-python-api-backend#6]
Traceback (most recent call last):
  File "./postgres/import_referrers.py", line 33, in <module>
    cur.execute(query)
psycopg2.ProgrammingError: relation "referrers" does not exist
LINE 1: SELECT rid FROM referrers ORDER BY rid DESC LIMIT 1

**Comment by knaperek** [comment]
I confirm this is happening, here's how to reproduce it easily with Docker:

```bash
$ cd bitshares-python-api-backend/
$ docker-compose run --rm realtime-importer python ./postgres/import_assets.py
```
Reproducibility 100%, just run the command and wait for about 5 seconds.

@hiquanta I think the title would be more readable like this:
> schema.txt is not up to date: column and table missing
Please update the title if you agree :-)

**Update:** Also the `referrers` table is missing:
```python
Traceback (most recent call last):
  File "./postgres/import_referrers.py", line 33, in <module>
    cur.execute(query)
psycopg2.ProgrammingError: relation "referrers" does not exist
LINE 1: SELECT rid FROM referrers ORDER BY rid DESC LIMIT 1
```

**Comment by oxarbitrage** [comment]
updated schema https://github.com/oxarbitrage/bitshares-python-api-backend/commit/108ffc6c143a8d17ad84d900910a3dba99e3b60b
