### ISSUE TITLE
Explorer is not available

### ISSUE THREAD

**Issue by 1scrooge** [oxarbitrage/bitshares-python-api-backend#75]
Hi 
Any chance to fix https://explorer.bitshares-kibana.info ?

**Comment by sschiessl-bcp** [comment]
That service was operated by @oxarbitrage in his free time while working for the core worker. Since that has ceased please expect this service to stay unavailable until further notice.

**Comment by oxarbitrage** [comment]
What @sschiessl-bcp stated is true, i am not maintaining the services anymore however i do still have some of them up. In the case of the one mentioned i had it running connected to the infrastructure elasticsearch node which is working fine at the moment. Problem was disk full on my side so i deleted my ES data and restarted the service, is up now:

https://explorer.bitshares-kibana.info/apidocs/

Thanks for letting me know.

**Comment by 1scrooge** [comment]
Thanks @oxarbitrage  for update
